import {
  slate,
  slateA,
  gold as rGold,
  goldA as rGoldA,
  iris as rIris,
  irisA as rIrisA,
  green as rGreen,
  greenA as rGreenA,
  orange as rOrange,
  orangeA as rOrangeA,
  blue as rBlue,
  blueA as rBlueA,
  lime as rLime,
  limeA as rLimeA,
  cyan as rCyan,
  cyanA as rCyanA,
  purple as rPurple,
  purpleA as rPurpleA,
  yellow as rYellow,
  yellowA as rYellowA,
} from "@radix-ui/colors";

export const sky = {
  sky1: "#f9fdff",
  sky2: "#f1fafe",
  sky3: "#dbf7ff",
  sky4: "#c6f1ff",
  sky5: "#b0e9fb",
  sky6: "#96ddf4",
  sky7: "#73ceea",
  sky8: "#19b9df",
  sky9: "#21bce2",
  sky10: "#00b0d6",
  sky11: "#007c9c",
  sky12: "#003e4d",
};

export const skyA = {
  skyA1: "#00aaff06",
  skyA2: "#00a4ed0e",
  skyA3: "#00c7ff24",
  skyA4: "#00c1ff39",
  skyA5: "#00b8f34f",
  skyA6: "#00ade569",
  skyA7: "#00a6d98c",
  skyA8: "#00b1dce6",
  skyA9: "#00b2dede",
  skyA10: "#00b0d6",
  skyA11: "#007c9c",
  skyA12: "#003e4d",
};

export const gray = {
  gray1: slate.slate1,
  gray2: slate.slate2,
  gray3: slate.slate3,
  gray4: slate.slate4,
  gray5: slate.slate5,
  gray6: slate.slate6,
  gray7: slate.slate7,
  gray8: slate.slate8,
  gray9: slate.slate9,
  gray10: slate.slate10,
  gray11: slate.slate11,
  gray12: slate.slate12,
};

export const grayA = {
  grayA1: slateA.slateA1,
  grayA2: slateA.slateA2,
  grayA3: slateA.slateA3,
  grayA4: slateA.slateA4,
  grayA5: slateA.slateA5,
  grayA6: slateA.slateA6,
  grayA7: slateA.slateA7,
  grayA8: slateA.slateA8,
  grayA9: slateA.slateA9,
  grayA10: slateA.slateA10,
  grayA11: slateA.slateA11,
  grayA12: slateA.slateA12,
};

export const gold = {
  gold1: rGold.gold1,
  gold2: rGold.gold2,
  gold3: rGold.gold3,
  gold4: rGold.gold4,
  gold5: rGold.gold5,
  gold6: rGold.gold6,
  gold7: rGold.gold7,
  gold8: rGold.gold8,
  gold9: rGold.gold9,
  gold10: rGold.gold10,
  gold11: rGold.gold11,
  gold12: rGold.gold12,
};

export const goldA = {
  goldA1: rGoldA.goldA1,
  goldA2: rGoldA.goldA2,
  goldA3: rGoldA.goldA3,
  goldA4: rGoldA.goldA4,
  goldA5: rGoldA.goldA5,
  goldA6: rGoldA.goldA6,
  goldA7: rGoldA.goldA7,
  goldA8: rGoldA.goldA8,
  goldA9: rGoldA.goldA9,
  goldA10: rGoldA.goldA10,
  goldA11: rGoldA.goldA11,
  goldA12: rGoldA.goldA12,
};

export const iris = {
  iris1: rIris.iris1,
  iris2: rIris.iris2,
  iris3: rIris.iris3,
  iris4: rIris.iris4,
  iris5: rIris.iris5,
  iris6: rIris.iris6,
  iris7: rIris.iris7,
  iris8: rIris.iris8,
  iris9: rIris.iris9,
  iris10: rIris.iris10,
  iris11: rIris.iris11,
  iris12: rIris.iris12,
};

export const irisA = {
  irisA1: rIrisA.irisA1,
  irisA2: rIrisA.irisA2,
  irisA3: rIrisA.irisA3,
  irisA4: rIrisA.irisA4,
  irisA5: rIrisA.irisA5,
  irisA6: rIrisA.irisA6,
  irisA7: rIrisA.irisA7,
  irisA8: rIrisA.irisA8,
  irisA9: rIrisA.irisA9,
  irisA10: rIrisA.irisA10,
  irisA11: rIrisA.irisA11,
  irisA12: rIrisA.irisA12,
};

export const green = {
  green1: rGreen.green1,
  green2: rGreen.green2,
  green3: rGreen.green3,
  green4: rGreen.green4,
  green5: rGreen.green5,
  green6: rGreen.green6,
  green7: rGreen.green7,
  green8: rGreen.green8,
  green9: rGreen.green9,
  green10: rGreen.green10,
  green11: rGreen.green11,
  green12: rGreen.green12,
};

export const greenA = {
  greenA1: rGreenA.greenA1,
  greenA2: rGreenA.greenA2,
  greenA3: rGreenA.greenA3,
  greenA4: rGreenA.greenA4,
  greenA5: rGreenA.greenA5,
  greenA6: rGreenA.greenA6,
  greenA7: rGreenA.greenA7,
  greenA8: rGreenA.greenA8,
  greenA9: rGreenA.greenA9,
  greenA10: rGreenA.greenA10,
  greenA11: rGreenA.greenA11,
  greenA12: rGreenA.greenA12,
};

export const orange = {
  orange1: rOrange.orange1,
  orange2: rOrange.orange2,
  orange3: rOrange.orange3,
  orange4: rOrange.orange4,
  orange5: rOrange.orange5,
  orange6: rOrange.orange6,
  orange7: rOrange.orange7,
  orange8: rOrange.orange8,
  orange9: rOrange.orange9,
  orange10: rOrange.orange10,
  orange11: rOrange.orange11,
  orange12: rOrange.orange12,
};

export const orangeA = {
  orangeA1: rOrangeA.orangeA1,
  orangeA2: rOrangeA.orangeA2,
  orangeA3: rOrangeA.orangeA3,
  orangeA4: rOrangeA.orangeA4,
  orangeA5: rOrangeA.orangeA5,
  orangeA6: rOrangeA.orangeA6,
  orangeA7: rOrangeA.orangeA7,
  orangeA8: rOrangeA.orangeA8,
  orangeA9: rOrangeA.orangeA9,
  orangeA10: rOrangeA.orangeA10,
  orangeA11: rOrangeA.orangeA11,
  orangeA12: rOrangeA.orangeA12,
};

export const blue = {
  blue1: rBlue.blue1,
  blue2: rBlue.blue2,
  blue3: rBlue.blue3,
  blue4: rBlue.blue4,
  blue5: rBlue.blue5,
  blue6: rBlue.blue6,
  blue7: rBlue.blue7,
  blue8: rBlue.blue8,
  blue9: rBlue.blue9,
  blue10: rBlue.blue10,
  blue11: rBlue.blue11,
  blue12: rBlue.blue12,
};

export const blueA = {
  blueA1: rBlueA.blueA1,
  blueA2: rBlueA.blueA2,
  blueA3: rBlueA.blueA3,
  blueA4: rBlueA.blueA4,
  blueA5: rBlueA.blueA5,
  blueA6: rBlueA.blueA6,
  blueA7: rBlueA.blueA7,
  blueA8: rBlueA.blueA8,
  blueA9: rBlueA.blueA9,
  blueA10: rBlueA.blueA10,
  blueA11: rBlueA.blueA11,
  blueA12: rBlueA.blueA12,
};

export const lime = {
  lime1: rLime.lime1,
  lime2: rLime.lime2,
  lime3: rLime.lime3,
  lime4: rLime.lime4,
  lime5: rLime.lime5,
  lime6: rLime.lime6,
  lime7: rLime.lime7,
  lime8: rLime.lime8,
  lime9: rLime.lime9,
  lime10: rLime.lime10,
  lime11: rLime.lime11,
  lime12: rLime.lime12,
};

export const limeA = {
  limeA1: rLimeA.limeA1,
  limeA2: rLimeA.limeA2,
  limeA3: rLimeA.limeA3,
  limeA4: rLimeA.limeA4,
  limeA5: rLimeA.limeA5,
  limeA6: rLimeA.limeA6,
  limeA7: rLimeA.limeA7,
  limeA8: rLimeA.limeA8,
  limeA9: rLimeA.limeA9,
  limeA10: rLimeA.limeA10,
  limeA11: rLimeA.limeA11,
  limeA12: rLimeA.limeA12,
};

export const cyan = {
  cyan1: rCyan.cyan1,
  cyan2: rCyan.cyan2,
  cyan3: rCyan.cyan3,
  cyan4: rCyan.cyan4,
  cyan5: rCyan.cyan5,
  cyan6: rCyan.cyan6,
  cyan7: rCyan.cyan7,
  cyan8: rCyan.cyan8,
  cyan9: rCyan.cyan9,
  cyan10: rCyan.cyan10,
  cyan11: rCyan.cyan11,
  cyan12: rCyan.cyan12,
};

export const cyanA = {
  cyanA1: rCyanA.cyanA1,
  cyanA2: rCyanA.cyanA2,
  cyanA3: rCyanA.cyanA3,
  cyanA4: rCyanA.cyanA4,
  cyanA5: rCyanA.cyanA5,
  cyanA6: rCyanA.cyanA6,
  cyanA7: rCyanA.cyanA7,
  cyanA8: rCyanA.cyanA8,
  cyanA9: rCyanA.cyanA9,
  cyanA10: rCyanA.cyanA10,
  cyanA11: rCyanA.cyanA11,
  cyanA12: rCyanA.cyanA12,
};

export const purple = {
  purple1: rPurple.purple1,
  purple2: rPurple.purple2,
  purple3: rPurple.purple3,
  purple4: rPurple.purple4,
  purple5: rPurple.purple5,
  purple6: rPurple.purple6,
  purple7: rPurple.purple7,
  purple8: rPurple.purple8,
  purple9: rPurple.purple9,
  purple10: rPurple.purple10,
  purple11: rPurple.purple11,
  purple12: rPurple.purple12,
};

export const purpleA = {
  purpleA1: rPurpleA.purpleA1,
  purpleA2: rPurpleA.purpleA2,
  purpleA3: rPurpleA.purpleA3,
  purpleA4: rPurpleA.purpleA4,
  purpleA5: rPurpleA.purpleA5,
  purpleA6: rPurpleA.purpleA6,
  purpleA7: rPurpleA.purpleA7,
  purpleA8: rPurpleA.purpleA8,
  purpleA9: rPurpleA.purpleA9,
  purpleA10: rPurpleA.purpleA10,
  purpleA11: rPurpleA.purpleA11,
  purpleA12: rPurpleA.purpleA12,
};

export const yellow = {
  yellow1: rYellow.yellow1,
  yellow2: rYellow.yellow2,
  yellow3: rYellow.yellow3,
  yellow4: rYellow.yellow4,
  yellow5: rYellow.yellow5,
  yellow6: rYellow.yellow6,
  yellow7: rYellow.yellow7,
  yellow8: rYellow.yellow8,
  yellow9: rYellow.yellow9,
  yellow10: rYellow.yellow10,
  yellow11: rYellow.yellow11,
  yellow12: rYellow.yellow12,
};

export const yellowA = {
  yellowA1: rYellowA.yellowA1,
  yellowA2: rYellowA.yellowA2,
  yellowA3: rYellowA.yellowA3,
  yellowA4: rYellowA.yellowA4,
  yellowA5: rYellowA.yellowA5,
  yellowA6: rYellowA.yellowA6,
  yellowA7: rYellowA.yellowA7,
  yellowA8: rYellowA.yellowA8,
  yellowA9: rYellowA.yellowA9,
  yellowA10: rYellowA.yellowA10,
  yellowA11: rYellowA.yellowA11,
  yellowA12: rYellowA.yellowA12,
};
